In [4]:
import pandas as pd
import numpy as np

In [5]:
placement = pd.read_csv("Placement_BeginnerTask01.csv")

In [6]:
placement

StudentID  CGPA  Internships  Projects  Workshops/Certifications  \
0             1   7.5            1         1                         1   
1             2   8.9            0         3                         2   
2             3   7.3            1         2                         2   
3             4   7.5            1         1                         2   
4             5   8.3            1         2                         2   
...         ...   ...          ...       ...                       ...   
9995       9996   7.5            1         1                         2   
9996       9997   7.4            0         1                         0   
9997       9998   8.4            1         3                         0   
9998       9999   8.9            0         3                         2   
9999      10000   8.4            0         1                         1   

      AptitudeTestScore  SoftSkillsRating ExtracurricularActivities  \
0                    65               4.4                        No   
1                    90               4.0                       Yes   
2                    82               4.8                       Yes   
3                    85               4.4                       Yes   
4                    86               4.5                       Yes   
...                 ...               ...                       ...   
9995                 72               3.9                       Yes   
9996                 90               4.8                        No   
9997                 70               4.8                       Yes   
9998                 87               4.8                       Yes   
9999                 66               3.8                        No   

     PlacementTraining  SSC_Marks  HSC_Marks PlacementStatus  
0                   No         61         79       NotPlaced  
1                  Yes         78         82          Placed  
2                   No         79         80       NotPlaced  
3                  Yes         81         80          Placed  
4                  Yes         74         88          Placed  
...                ...        ...        ...             ...  
9995                No         85         66       NotPlaced  
9996                No         84         67          Placed  
9997               Yes         79         81          Placed  
9998               Yes         71         85          Placed  
9999                No         62         66       NotPlaced  

[10000 rows x 12 columns]

In [7]:
placement.drop("StudentID", axis=1, inplace=True)

In [8]:
placement.dtypes

CGPA                         float64
Internships                    int64
Projects                       int64
Workshops/Certifications       int64
AptitudeTestScore              int64
SoftSkillsRating             float64
ExtracurricularActivities     object
PlacementTraining             object
SSC_Marks                      int64
HSC_Marks                      int64
PlacementStatus               object
dtype: object

In [9]:
placement["ExtracurricularActivities"] = placement["ExtracurricularActivities"].astype("category")
placement["PlacementTraining"] = placement["PlacementTraining"].astype("category")
placement["PlacementStatus"] = placement["PlacementStatus"].astype("category")

In [10]:
placement.dtypes

CGPA                          float64
Internships                     int64
Projects                        int64
Workshops/Certifications        int64
AptitudeTestScore               int64
SoftSkillsRating              float64
ExtracurricularActivities    category
PlacementTraining            category
SSC_Marks                       int64
HSC_Marks                       int64
PlacementStatus              category
dtype: object

In [11]:
x = placement.drop("PlacementStatus", axis=1)
y = placement["PlacementStatus"]

In [16]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

cat_cols = ("ExtracurricularActivities", "PlacementTraining")
transformer = ColumnTransformer([("cols", OneHotEncoder(), cat_cols)], remainder = "passthrough")
transformed_x = transformer.fit_transform(x)

transformed_x

array([[ 1. ,  0. ,  1. , ...,  4.4, 61. , 79. ],
       [ 0. ,  1. ,  0. , ...,  4. , 78. , 82. ],
       [ 0. ,  1. ,  1. , ...,  4.8, 79. , 80. ],
       ...,
       [ 0. ,  1. ,  0. , ...,  4.8, 79. , 81. ],
       [ 0. ,  1. ,  0. , ...,  4.8, 71. , 85. ],
       [ 1. ,  0. ,  1. , ...,  3.8, 62. , 66. ]], shape=(10000, 12))

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(transformed_x, y, test_size=0.2)

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
clf = RandomForestClassifier()

In [21]:
clf.fit(x_train, y_train)

RandomForestClassifier()

In [57]:
y_preds = clf.predict(x_test)
clf.score(x_test, y_test)

0.781

In [54]:
from sklearn.model_selection import cross_val_score
cross_val_score(clf, transformed_x, y, cv=5)
mean = np.mean(cross_val_score(clf, transformed_x, y, cv=5))
mean

np.float64(0.7869999999999999)

In [49]:
from sklearn.linear_model import LogisticRegression

clf1 = LogisticRegression(max_iter=1000)

In [59]:
clf1.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [60]:
y_preds1 = clf1.predict(x_test)
clf1.score(x_test, y_test)

0.7865

In [56]:
mean1 = np.mean(cross_val_score(clf1, transformed_x, y, cv=5))
mean1

np.float64(0.7998000000000001)

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [61]:
print(confusion_matrix(y_test, y_preds))

[[987 206]
 [232 575]]


In [62]:
print(confusion_matrix(y_test, y_preds1))

[[960 233]
 [194 613]]


#Model 2 is better as seen